unit TestAddressClass;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Dialogs, AddressClass, System.SysUtils;

type
  // Test methods for class TAdrressClass

  TestTAdrressClass = class(TTestCase)
  strict private
    FAdrressClass: TAddressClass;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestToString;
  end;

implementation

procedure TestTAdrressClass.SetUp;
begin
  FAdrressClass := TAddressClass.Create('12345-678', 'Rua das Flores, 123', 'Apto 101', 'Jardim Alegre',
    'São Paulo', 'SP', '3550308', '', '11', '8976');
end;

procedure TestTAdrressClass.TearDown;
begin
  FAdrressClass.Free;
  FAdrressClass := nil;
end;

procedure TestTAdrressClass.TestToString;
var
  ReturnValue: string;
begin
  ReturnValue := FAdrressClass.ToString;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAdrressClass.Suite);
end.

